function buildUI1(obj)
    obj.hfig=figure('pos',obj.viewSize,'NumberTitle','off','Menubar','none',...
        'Toolbar','none');
    obj.drawButton=uicontrol('Parent',obj.hfig,'string','deposit',...
        'pos',[180 28 60 28]);
    obj.depositButton=uicontrol('Parent',obj.hfig,'string','deposit',...
        'pos',[60 85 180 28]);
    obj.numBox=uicontrol('Parent',obj.hfig,'Style','edit',...
        'pos',[60 85 180 28]);
    obj.text=uicontrol('Parent',obj.hfig,'style','text','string','Balance',...
        'pos',[60142 60 28]);
    obj.balanceBox=uicontrol('Parent',pbj.hfig,'style','edit',...
        'pos',[180 142 60 28],'tag','balanceBox');
    obj.updateBalance();
end
